# Generated by Django 5.1.6 on 2025-02-13 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('on_road_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('lat', models.CharField(max_length=50)),
                ('lon', models.CharField(max_length=50)),
                ('estReachDist', models.CharField(default='-', max_length=100)),
                ('estReachTime', models.CharField(default='-', max_length=100)),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('rate', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=50)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='on_road_app.customer')),
                ('mechanic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='on_road_app.mechanic')),
            ],
        ),
    ]
