# Generated by Django 5.1.6 on 2025-02-13 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('on_road_app', '0002_bookings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='on_road_app.customer'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='mechanic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='on_road_app.mechanic'),
        ),
    ]
