# Generated by Django 5.1.6 on 2025-02-17 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('on_road_app', '0005_fire'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='review',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
