# Generated by Django 5.1.6 on 2025-02-17 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('on_road_app', '0007_remove_bookings_review_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='user',
            new_name='customer',
        ),
        migrations.AddField(
            model_name='feedback',
            name='feedback',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
