# Generated by Django 5.1.6 on 2025-02-17 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('on_road_app', '0008_rename_user_feedback_customer_feedback_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='feedback',
            field=models.CharField(default='-', max_length=300, null=True),
        ),
    ]
