# Generated by Django 5.1.6 on 2025-02-17 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('on_road_app', '0009_alter_feedback_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='review',
            field=models.BooleanField(default=0),
        ),
    ]
