# Generated by Django 5.1.6 on 2025-02-17 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('on_road_app', '0010_bookings_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='mechanic',
        ),
    ]
