# Generated by Django 5.1.6 on 2025-02-17 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('on_road_app', '0011_remove_feedback_customer_remove_feedback_mechanic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
